name: default

# Anchor filtering
anchor_level: null
excluded: null
unrelated: null
relation_margin: null
distance_margin: null

# Positive filtering
positive_level: null
positive_relation: null
positive_distance: null
n_positives: 64

# Negative sampling
negative_level: null
negative_relation: null
negative_distance: null
n_negatives: 32