# Trainer Configuration: conf/trainer/default.yaml
_target_: pytorch_lightning.Trainer

# --- Hardware ---
accelerator: "auto"
devices: "auto"
precision: "bf16-mixed" # Use "16-mixed" for older GPUs

# --- Training Control ---
max_epochs: 5
log_every_n_steps: 10
val_check_interval: 0.1 # Check validation set every 10% of an epoch

# --- Callbacks ---
default_root_dir: ${paths.output_dir}
enable_checkpointing: true
enable_progress_bar: true
